            - name: Flutter Environment
  # You may pin to the exact commit or the version.
  # uses: arxdeus/flutter-action@c91349235d2f948c622f956b474cdd5caa904f33
  uses: arxdeus/flutter-action@v1
  with:
    # The Flutter version to make available on the path
    flutter-version: # optional, default is stable
    # Cache the Flutter SDK
    cache: # optional, default is true
    # Identifier for the Flutter SDK cache
    cache-key: # optional, default is 
    # Flutter SDK cache path
    cache-path: # optional, default is /home/runner/opt/flutter
    # Identifier for the Dart .pub-cache cache
    pub-cache-key: # optional, default is 
    # Flutter pub cache path
    pub-cache-path: # optional, default is /home/runner/cache/pub
    # Git clone source
    git-source: # optional, default is https://github.com/flutter/flutter.git
          
